language: node_js
node_js:
  - "stable"
  - "5"
  - "5.1"
  - "6"

env:
  - ENV="development"

install:
  - npm install

before_script:
  - npm install -g gulp

after_success: 'npm run coveralls'

script: npm test